# travis-ci integration for KiBOM

dist: xenial

language: python

python:
  - 3.6

install:
  - pip install -r test/requirements.txt

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install python3-pip python3-coverage python3-xlsxwriter

script:
  # Check Python code for style-guide 
  - flake8 .
  # Run the coverage tests 
  - bash ./run-tests.sh

after_success:
  - coveralls